FROM ubuntu

RUN apt-get update
RUN apt-get install -y vim
RUN apt-get install -y binutils
RUN apt-get update
RUN apt-get install gcc-multilib

WORKDIR /home/dinara

RUN git clone https://github.com/dinarazhunisbekova/sp_lab2.git \
    && cd sp_lab2.git/

WORKDIR /home/dinara/sp_lab2/
